package com.drop.shiping.api.drop_shiping_api.payments.dtos;

public record EpaycoWebhookDTO(
    String refPayco,
    String xCustIdCliente,
    String xRefPayco,
    String xIdInvoice,
    String xDescription,
    String xAmount,
    String xAmountCountry,
    String xAmountOk,
    String xTax,
    String xAmountBase,
    String xCurrencyCode,
    String xTransactionId,
    String xResponse, // Aceptada, Rechazada, Pendiente, Fallida
    String xApprovalCode,
    String xResponseReasonText,
    String xTransactionDate,
    String xTransactionState,
    String xFranchise,
    String xBusiness,
    String xCustomerDoctype,
    String xCustomerDocument,
    String xCustomerName,
    String xCustomerLastname,
    String xCustomerEmail,
    String xCustomerPhone,
    String xCustomerCountry,
    String xCustomerCity,
    String xCustomerAddress,
    String xCustomerIp,
    String xSignature,
    String xTestRequest,
    String xExtra1,
    String xExtra2,
    String xExtra3,
    String xExtra4,
    String xExtra5,
    String xExtra6,
    String xExtra7,
    String xExtra8,
    String xExtra9,
    String xExtra10
) {
}
